### ISSUE TITLE
Nukkit Crash

### ISSUE THREAD

**Issue by HyGlobalHD** [fengberd/MinecraftPEServer#1]
---

[PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/data/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/sdcard0/Nukkit/Nukkit.jar, enable-ansi, disable-jline] Working Directory: /storage/sdcard0/Nukkit Environment: [ANDROID_SOCKET_zygote=9, SECONDARY_STORAGE=/storage/sdcard1, ANDROID_STORAGE=/storage, TMPDIR=/storage/sdcard0/Nukkit/tmp, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/sdcard0, LD_PRELOAD=/system/lib/libNimsWrap.so, ANDROID_ASSETS=/system/app, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ASEC_MOUNTPOINT=/mnt/asec, LOOP_MOUNTPOINT=/mnt/obb, BOOTCLASSPATH=/system/framework/core.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework_ext.jar:/system/framework/telephony-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/telephony-msim.jar:/system/framework/qcmediaplayer.jar:/system/framework/WfdCommon.jar, ANDROID_DATA=/data, LD_LIBRARY_PATH=/vendor/lib:/system/lib, ANDROID_ROOT=/system, ANDROID_PROPERTY_WORKSPACE=8,65536]

---

**Comment by fengberd** [comment]
Opps,you should mount the java library before you run Nukkit every times.I'm sorry but I can't solve this question because java just look up its library in /lib
