### ISSUE TITLE
couldnt start nukkit.

### ISSUE THREAD

**Issue by haniokasai** [fengberd/MinecraftPEServer#10]
i tried starting nukkit.but
[PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/data/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/emulated/0/Nukkit/Nukkit.jar, disable-ansi, disable-jline] Working Directory: /storage/emulated/0/Nukkit Environment: [ANDROID_ROOT=/system, EMULATED_STORAGE_SOURCE=/mnt/shell/emulated, LOOP_MOUNTPOINT=/mnt/obb, LD_PRELOAD=libsigchain.so:libudf.so, USBOTG_STORAGE=/storage/usbotg, MC_AUTH_TOKEN_PATH=/efs, ANDROID_BOOTLOGO=1, EMULATED_STORAGE_TARGET=/storage/emulated, EXTERNAL_STORAGE=/storage/emulated/legacy, TMPDIR=/storage/emulated/0/Nukkit/tmp, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=10, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar:/system/app/miui/miui.apk:/system/app/miuisystem/miuisystem.apk, ANDROID_PROPERTY_WORKSPACE=8,0, SECONDARY_STORAGE=/storage/sdcard1, ANDROID_STORAGE=/storage]

**Comment by HyGlobalHD** [comment]
1) Your Phone Must Root.
2) If you using android don't use ku.sud
3) Every time you want to start the server press mount Java Library
4) Make Sure You Already Install Nukkit.jar
5) Start Your Server

**Comment by haniokasai** [comment]
all done,but it happened.

**Comment by HyGlobalHD** [comment]
but... I can use it finely..

**Comment by haniokasai** [comment]
use busybox?

**Comment by HyGlobalHD** [comment]
no I don't use busybox.
between have u tried download java, at the menu?

**Comment by haniokasai** [comment]
no there isnt  download java button.
so i downloaded from https://www.dropbox.com/s/c6xnyehgdtwobct/nukkit_library.tar.gz?dl=0

**Comment by cws06099** [comment]
me too.
i can't start server because it happened.

my phone model is LG F490L
also use kitkat 4.4.4

**Comment by cws06099** [comment]
It seems not to work Java library

**Comment by fengberd** [comment]
Use a terminal to exec this command after you mounted the library:
ls /lib
If there's nothing or just a file not exists notice,maybe your ROM not support this function...
