### ISSUE TITLE
PHP 7.0.9 for Genisys with OpenSSL

### ISSUE THREAD

**Issue by dktapps** [fengberd/MinecraftPEServer#11]
Please add [this PHP 7.0.9 binary with OpenSSL](https://itxtech.org/download/PHP%20for%20Genisys/php_7.0.9_linux_arm.xz) to your repository. An upcoming Genisys update will add Xbox Live authentication and requires OpenSSL.

Also, could you add an option to install a custom PHP binary from local storage? That would make things a whole load easier in circumstances like this so I don't have to recompile the app.

**Comment by fengberd** [comment]
OK,see [this commit](https://github.com/fengberd/MinecraftPEServer/commit/29118699cdfd14ff38cfe8745acf2ded7b9140ec)

**Comment by fengberd** [comment]
WTF??
The PHP binary you provided don't have pthread extension??!

**Comment by Yoyu666** [comment]
@dktapps Just send me the file u give me... :package: 
@fengberd  我已经Update 我的 Php 到 7.0.9了，请你等待(づ ●─● )づ

**Comment by dktapps** [comment]
He just had a corrupted download. The issue has been resolved.
