### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by HyGlobalHD** [fengberd/MinecraftPEServer#12]
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.
[PE Server] Server was stopped.

Every Times I Try Download The php7.tar.gz from the Download & Install PHP7 it will shown the above message when i start the server
then i try Install PHP button it shown the error below:

[CRITICAL] You must use PHP >= 7.0
[CRITICAL] Please use the installer provided on the homepage.
[PE Server] Server was stopped.

if this kind of mistake please help ..

**Comment by fengberd** [comment]
OMG,I got this binary from iTXTech's website but it don't have pthread extension...I'm asking the author for a new binary,please be patient!

**Comment by fengberd** [comment]
Fixed in [this commit](https://github.com/fengberd/MinecraftPEServer/commit/9570aa93558bc65b624c6ed1e8b5cd0605f2e828)
Thanks for your reporting
