### ISSUE TITLE
Incompatible Java Library On Android 5.0+

### ISSUE THREAD

**Issue by milkice233** [fengberd/MinecraftPEServer#13]
Feeling weird,but the java library you provided partly doesn't work well on Android 5.0+.
For example,connecting to any sites(domain not ip) will throw an Exception said that unable to solve the address with unknow error.
I'm wondering if any other bug exists,but if it's acceptable, updating the java library may be a good choice?

**Comment by fengberd** [comment]
I got java library from oracle.com,you can download a new one and pack it like what I provided then install it.
