### ISSUE TITLE
JVM Crashes when starting a server.

### ISSUE THREAD

**Issue by jimchen5209** [fengberd/MinecraftPEServer#14]
JVM Crashes when starting a nukkit server.

**Crash log:**
[hs_err_pid7277.log.txt](https://github.com/fengberd/MinecraftPEServer/files/429841/hs_err_pid7277.log.txt)

**Full log:**

> [0;36;1m10:13:10 [0;37;1m[INFO] [0;32;1mWelcome! Please choose a language first!
> [0;36;1m10:13:10 [0;37;1m[INFO] eng => English
> [0;36;1m10:13:10 [0;37;1m[INFO] chs => ??????
> [0;36;1m10:13:10 [0;37;1m[INFO] cht => ??????
> [0;36;1m10:13:10 [0;37;1m[INFO] jpn => ???
> [0;36;1m10:13:10 [0;37;1m[INFO] rus => Pycc???
> [0;36;1m10:13:10 [0;37;1m[INFO] spa => Espa?ol
> [0;36;1m10:13:10 [0;37;1m[INFO] pol => Polish
> [0;36;1m10:13:10 [0;37;1m[INFO] bra => Portugu?s-Brasil
> [0;36;1m10:13:10 [0;37;1m[INFO] kor => ???
>  eng 
> [0;36;1m10:13:21 [0;37;1m[INFO] Loading [0;32;1mnukkit.yml[0;37;1m...
> [0;36;1m10:13:21 [0;37;1m[INFO] Loading [0;32;1mserver properties[0;37;1m...
> [0;36;1m10:13:21 [0;37;1m[INFO] Selected English (eng) as the base language
> [0;36;1m10:13:21 [0;37;1m[INFO] Starting Minecraft: PE server version [0;36;1mv0.15.6 alpha[0;37;1m
> [0;36;1m10:13:22 [0;37;1m[INFO] Opening server on 0.0.0.0:19132
> [0;36;1m10:13:22 [0;37;1m[INFO] This server is running Nukkit version [0;33;1m1.0dev[0;37;1m "[0;36;1m??(Apple)?(Pie)[0;37;1m" (API 1.0.0)
> [0;36;1m10:13:22 [0;37;1m[INFO] Nukkit is distributed under the LGPL License
> [0;36;1m10:13:23 [0;36;1m[NOTICE] Level "world" not found
> =============== DEBUG MESSAGE: Atomic load(jlong) unsupported on this platform ================
> # 
> #  A fatal error has been detected by the Java Runtime Environment:
> # 
> #   Internal Error (macroAssembler_arm.cpp:1727), pid=7277, tid=3800364144
> #   fatal error: Atomic load(jlong) unsupported on this platform
> # 
> #  JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
> #  Java VM: Java HotSpot(TM) Client VM (25.65-b01 mixed mode linux-arm )
> #  Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> # 
> #  An error report file with more information is saved as:
> #  /storage/emulated/0/Nukkit/hs_err_pid7277.log
> # 
> #  If you would like to submit a bug report, please visit:
> #    http://bugreport.java.com/bugreport/crash.jsp
> # 
> 
> [PE Server] Server was stopped.

**Comment by fengberd** [comment]
Oh,please report to oracle and submit your device information,I can't solve it..
