### ISSUE TITLE
How install nukkit 

### ISSUE THREAD

**Issue by KagiamyGame** [fengberd/MinecraftPEServer#15]
this is why
 [PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/user/0/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/emulated/0/Nukkit/Nukkit.jar, enable-ansi, disable-jline] Working Directory: /storage/emulated/0/Nukkit Environment: [ANDROID_ROOT=/system, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/sdcard, TMPDIR=/storage/emulated/0/Nukkit/tmp, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=11, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/dolby_ds.jar:/system/framework/dolby_ds2.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar, ANDROID_PROPERTY_WORKSPACE=9,0, ANDROID_STORAGE=/storage]
I have installed java?

**Comment by nnnlog** [comment]
Are you mount java?

**Comment by fengberd** [comment]
Mount java libs at first...If it not work after you do that please check /lib folder
