### ISSUE TITLE
Can not start server? 

### ISSUE THREAD

**Issue by Creeperface01** [fengberd/MinecraftPEServer#17]
I downloaded nukkit_library.tar.gz then i installed java then downloaded latest nukkit then i mounted java library then restart the device then mounted library again (for sure)  but i can not press start.. Whats wrong? 
![screenshot_2016-09-03-08-46-53](https://cloud.githubusercontent.com/assets/10363500/18223285/fc9ed780-71b2-11e6-857d-f865134a584b.png)

**Comment by nnnlog** [comment]
If you use Kingroot, you check Use ku.sud to request root

**Comment by Creeperface01** [comment]
Im using super SU

**Comment by nnnlog** [comment]
Retry download java library, install java, mount java

**Comment by fengberd** [comment]
Hmm,this means java not installed,please make sure your nukkit_library.tar.gz in correct path and install again
