### ISSUE TITLE
 Auto Restart Server

### ISSUE THREAD

**Issue by smlrrlms** [fengberd/MinecraftPEServer#19]
Please add auto restart option to this app

**Comment by Yoyu666** [comment]
i dont think need add,because u can just use a plugins to reload server ez

**Comment by smlrrlms** [comment]
and i am using ASR + looping script start.sh on Linux because ASR send stop command. and i am not using reload command because is not effective and sometimes create conflicts in plugins...

**Comment by fengberd** [comment]
Sorry,I'm studying in high school now so I have no time to do that.
If possible please add it by yourself and open pull request,thanks!
