### ISSUE TITLE
How Install App ?

### ISSUE THREAD

**Issue by KagiamyGame** [fengberd/MinecraftPEServer#2]
How Install App or you can give me apk
(sorry i bad English)

**Comment by HyGlobalHD** [comment]
Jezzz
https://github.com/fengberd/MinecraftPEServer/releases

**Comment by KagiamyGame** [comment]
Thanks

**Comment by KagiamyGame** [comment]
[PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/data/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/emulated/0/Nukkit/Nukkit.jar, enable-ansi, disable-jline] Working Directory: /storage/emulated/0/Nukkit Environment: [EMULATED_STORAGE_SOURCE=/mnt/shell/emulated, ANDROID_SOCKET_zygote=14, RK_ADEPT_DEVICE_SALT_FILE=/mnt/sdcard/.adobe-digital-editions/devicesalt, RK_ADOBE_DE_MOBILE=1, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/emulated/legacy, ASEC_MOUNTPOINT=/mnt/asec, RK_ADEPT_DEVICE_TYPE=mobile, RK_ADEPT_DEVICE_FILE=/mnt/sdcard/.adobe-digital-editions/device.xml, BOOTCLASSPATH=/system/framework/core.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar, EMULATED_STORAGE_TARGET=/storage/emulated, SECOND_VOLUME_STORAGE=/Removable/MicroSD, EBOOK_PAGE_VISIBLE_NUMBER=2?RK_ADEPT_DEVICE_TYPE=mobile, ANDROID_DATA=/data, LD_LIBRARY_PATH=/vendor/lib:/system/lib, ANDROID_ROOT=/system, RK_ADEPT_ACTIVATION_FILE=/mnt/sdcard/.adobe-digital-editions/activation.xml, ANDROID_STORAGE=/storage, TMPDIR=/storage/emulated/0/Nukkit/tmp, ADOBE_FONTS_DIR=/system/fonts/adobefonts/, ANDROID_ASSETS=/system/app, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, LOOP_MOUNTPOINT=/mnt/obb, RK_ADOBE_DE_DOC_FOLDER=/mnt/sdcard/Digital Editions, THIRD_VOLUME_STORAGE=/Removable/USBdisk1, ANDROID_PROPERTY_WORKSPACE=13,65535]

**Comment by Khristian-kun** [comment]
you need to install java, nd it needs root

**Comment by TheDiamondYT1** [comment]
I would recommend downloading on Google play to show support to the creator.

**Comment by fengberd** [comment]
Mount the java library every times...
