### ISSUE TITLE
php zip extension

### ISSUE THREAD

**Issue by smlrrlms** [fengberd/MinecraftPEServer#20]
Please rebuild php and add zip extension.

**Comment by nnnlog** [comment]
What?

**Comment by fengberd** [comment]
Sorry,this binary is provided by iTX Tech,please ask them for new binary and tell me

**Comment by nnnlog** [comment]
@samalero This is from iTX-Tech
if you want fix binary, you tell them after you have to @fengberd

**Comment by Saxavlax001** [comment]
fengberd,I found php7 with zip and weakref extension not from iTX-tech,can I upload it?Php is archived in zip.

**Comment by nnnlog** [comment]
@poustmal I always upload @iTXTech 's PHP binary.
But, It doesn't work!

**Comment by Saxavlax001** [comment]
I replaced the php5 from app in my phone with the php 7 I found using apk editor app,and works fine.
