### ISSUE TITLE
PHP 7.0.10 with WeakRef extension

### ISSUE THREAD

**Issue by dktapps** [fengberd/MinecraftPEServer#22]
~~We've released an updated PHP binary including the WeakRef extension, which was for some reason missing from previous builds. Please update your repository. ([Download link](https://storage.googleapis.com/itx-technologies-141911.appspot.com/php_for_genisys/php_linux_7.0.10_arm.xz))~~

EDIT: the current binary has some issues. I'll update the issue once we have a working version.

(P.S. Could you update the app in Play Store please? Thanks :))

**Comment by fengberd** [comment]
If you have any problems about the php binary please ask iTX Tech for help,and let me know if they updated the binary that they provided,thanks.

**Comment by dktapps** [comment]
I _am_ iTXTech. I was letting you know we updated, but it ran into some issues.

**Comment by nnnlog** [comment]
@fengberd, @dktapps is iTX Member
