### ISSUE TITLE
Can't start server (Stops immediately after I start server)

### ISSUE THREAD

**Issue by Johnmacrocraft** [fengberd/MinecraftPEServer#27]
Same with the title. When I try to start server (PocketMine-MP type with Genisys), it stops immediately without any error. The only thing I can get is **[PE Server] Server was stopped.** message. Before it worked fine, but recently it started not to work! I also deleted PocketServer application data and cache, delete PocketMine folder, using Download server feature, but none of them worked! (To clarify, it doesn't mean these 3 tries didn't work - it means these 3 tries didn't allow me to start server.)

**Comment by nnnlog** [comment]
@Johnmacrocraft Plz say Korean, too

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 제목과 같습니다. 서버 (PocketMine-MP 형식으로 Genisys)를 킬려고 하면 오류 없이 바로 서버가 꺼집니다. 이 과정에서 유일하게 얻을 수 있는 것은 (발생하는 것은) **[PE Server] Server was stopped. (서버가 종료되었습니다.)** 메시지 입니다. 이전에는 잘 작동했는데, 갑자기 최근 들어서 작동하지 않습니다! PocketServer 애플리케이션 데이터 및 캐시도 지우고, PocketMine 폴더도 지우고, Download server (서버 다운로드) 기능도 사용해 보았지만, 아무것도 작동하지 않았습니다!

**Comment by nnnlog** [comment]
@Johnmacrocraft 조금 더 자세히 말씀해줏[ㅔ요
다운로드 서버(Download Server)기능에서 다운이 안된다는 건가요?

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 아뇨... 서버가 켜지지 않아서 PocketServer 애플리케이션 데이터 및 캐시도 지우고, PocketMine 폴더도 지우고, Download server (서버 다운로드) 기능도 사용해 보았지만 그래도 서버가 열리지 않았다는 말 입니다. 지금 보니까 마지막 문장이 충분히 님이 생각하신 것처럼 읽을 수 있겠네요.

**Comment by nnnlog** [comment]
@Johnmacrocraft php 7 다운 후 설치하셨나요?
동영상으로 님 블로그에 올려주신다면 참고해보도록 하겠습니다

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 당연히 PHP7은 설치했죠. PHP5를 설치하면 콘솔에 PHP 업데이트하라고 뺴애액 거리는 메시지가 뜨잖아요. 동영상은 약간 어려울 것 같습니다.

**Comment by nnnlog** [comment]
@Johnmacrocraft 그게 가장 확실한데... 스크린샷도 힘드나요?
한번 앱 데이터/캐시 삭제 -> 앱 삭제 -> 재부팅 -> 설치 과정을 다시한번 해주세요

**Comment by fengberd** [comment]
Maybe you have a broken PHP binary?
Or you blocked shell permission by some apps like XPrivaty...
I'm not very sure about that.

**Comment by nnnlog** [comment]
@fengberd I update php binary from itx-tech

**Comment by Johnmacrocraft** [comment]
@fengberd I downloaded php binary using PHP7 download feature with good network (I mean I don't think it's corrupted when downloading, I tried it multiple times). Also, my phone isn't rooted - it's pure (?).
Edit: All PHP7 cores (Genisys, ClearSky, PocketMine-MP) with PHP7 doesn't work, so I tried PHP5 core (PocketMine-MP) with PHP5. Result was works. Now I can say it seems PHP7 binary is broken.

**Comment by nnnlog** [comment]
@Johnmacrocraft Plz say korean...
대강보기에는 PHP 바이너리 문제라는 거 같긴한데(Now I can say it seems PHP7 binary is broken.)

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 답변이 늦었습니다만, 님이 생각하신대로 PHP 바이너리에 문제가 있는 것 같다고 말한겁니다.

PHP 바이너리를 PHP7 다운로드 기능으로 신호가 좋은 (다운로드 하다가 손상되서 그런거는 아닐겁니다. 여러 번 시도해봤거든요.) 네트워크로 다운로드 했습니다. 또한, 제 휴대전화는 루팅 안했습니다 - 순정이에요.
수정: 모든 PHP7 코어 (Genisys, ClearSky, PocketMine-MP)는 PHP7과 작동하지 않습니다. 그래서 PHP5 코어 (PocketMine-MP)를 PHP5로 실행해 봤습니다. (결과는) 잘 작동하더군요. 이제 PHP7 바이너리가 문제가 있다고 (고장났다고) 말할 수 있겠네요.

**Comment by nnnlog** [comment]
@Johnmacrocraft 아무래도 다시 컴파일 해야할거 같군요...

**Comment by nnnlog** [comment]
@Johnmacrocraft 한번 다시 플리퀘스트 작성해봤어요ㅡㅡ

**Comment by fengberd** [comment]
I'm sure about that php binary is version 7.0.9...You can download and run ./php -v
...
