### ISSUE TITLE
PHP 7 Binary doesn't work!

### ISSUE THREAD

**Issue by nnnlog** [fengberd/MinecraftPEServer#33]
Plz watch this post 
http://blog.naver.com/sorisem4106/220837337205

<iframe width="544" height="306" src="http://serviceapi.nmv.naver.com/flash/convertIframeTag.nhn?vid=D84BCFD244F0C32DCEBC24F54A5127B6B1C9&outKey=V1269ad320d8025f7500620b7933a170cba14c603e4c4d6c031fa20b7933a170cba14" frameborder="no" scrolling="no"></iframe>

**Comment by fengberd** [comment]
Please try to open a issue here.
https://github.com/iTXTech/Genisys

**Comment by nnnlog** [comment]
@fengberd I think this PR doesn't need.
