### ISSUE TITLE
Why cant i accept the license

### ISSUE THREAD

**Issue by annie289** [fengberd/MinecraftPEServer#34]
Why can't I accept the license I keep typing y
![screenshot_2016-10-21-21-22-08](https://cloud.githubusercontent.com/assets/22982059/19599888/1f254058-97d5-11e6-9873-0d9a976187eb.png)

**Comment by nnnlog** [comment]
What is version?(server)
ex) Genisys

**Comment by annie289** [comment]
If it's the ver of the app it's 1.0.7.4

**Comment by fengberd** [comment]
Ah,try to input more "y"
If it's not working,you can copy an server.properties from another server into /sdcard/PocketMine
