### ISSUE TITLE
0.16

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#38]
0.16 only says

[PE Server] Server stopped.

**Comment by nnnlog** [comment]
@Smasher535 This error re report to Genisys or PMMP, ClearSky

**Comment by ghost** [comment]
Clearsky and others work for pc PocketMine, theres a problem in Pocket Server

**Comment by nnnlog** [comment]
@Smasher535 Are you sure this error cause is PHP Binary problem?

**Comment by ghost** [comment]
Im not getting a error / crashdump so idk

**Comment by fengberd** [comment]
Is there any output else?

**Comment by nnnlog** [comment]
Picture please

**Comment by ghost** [comment]
![screenshot_2016-11-05-14-24-11](https://cloud.githubusercontent.com/assets/9281684/20030362/d4c113f8-a363-11e6-9e6b-e5290f0ae325.jpg)

Everything looks fine...

![screenshot_2016-11-05-14-24-18](https://cloud.githubusercontent.com/assets/9281684/20030366/e1946e54-a363-11e6-8fcd-b4af0283eb28.jpg)

Oh no!

Nothing more -_-

**Comment by fengberd** [comment]
Well,move to another issue
