### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by VCraftMCPE** [fengberd/MinecraftPEServer#39]
It always say 
[PE Server] Server was stopped.
1- I downloaded php 7
2- I used Genisys 15.10

**Comment by ghost** [comment]
YES!! FOR ME TOO!

**Comment by VCraftMCPE** [comment]
Yeah its the PHP 7 file

**Comment by nnnlog** [comment]
Oh, ...

**Comment by ghost** [comment]
![screenshot_2016-11-05-14-24-11](https://cloud.githubusercontent.com/assets/9281684/20030346/a6826a32-a363-11e6-8ab6-1997ebf3327a.jpg)

Everything looks fine....

![screenshot_2016-11-05-14-24-18](https://cloud.githubusercontent.com/assets/9281684/20030354/b5c562e2-a363-11e6-9085-4702c0df9a5b.jpg)

Oh no!

Nothing more -_-

**Comment by nnnlog** [comment]
@Smasher535 Oh!
What that situation?!?

I'll upload new php binary tommrow.(I'm Korean, The time is PM 10:28 . UTC +9)

**Comment by ghost** [comment]
Thx

**Comment by Johnmacrocraft** [comment]
@VCraftMCPE, @Smasher535, @ParkChanSol Also happens on me. (P.S: I actually reported this bug before (#27), but @fengberd closed it lol)

**Comment by nnnlog** [comment]
@Johnmacrocraft Your error solved. but, new php binary was problem again

님의 에러는 개선되었지만, 새로운 바이너리는 다시 문제를 일으키고 있습니다

**Comment by ghost** [comment]
STILL DOESN'T WORK!!!

**Comment by nnnlog** [comment]
@Smasher535 I knew

**Comment by Johnmacrocraft** [comment]
@VCraftMCPE, @Smasher535, @ParkChanSol I viewed the code of Pocket Server, and I just figured out it downloads PHP7 from here (Before I thought apk contains PHP7, so I tried downgrading to previous version): _https://raw.githubusercontent.com/FENGberd/MinecraftPEServer/master/_DOWNLOAD/php7.tar.gz_.

**Comment by nnnlog** [comment]
@Johnmacrocraft Korean

**Comment by ghost** [comment]
Just get the latest from php.net

**Comment by ghost** [comment]
http://se1.php.net/get/php-7.0.0.tar.gz/from/this/mirror

**Comment by nnnlog** [comment]
@Smasher535 Can I believe you link?

**Comment by ghost** [comment]
What do you mean?

**Comment by nnnlog** [comment]
@Smasher535 Oh, Can I believe you link? => Can I believe your link?

**Comment by ghost** [comment]
Its from PHP.net

**Comment by nnnlog** [comment]
@Smasher535 Does this binary work MINECRAFTPESERVER?

**Comment by ghost** [comment]
How the hell am I gonna know? Just test it ._.

**Comment by nnnlog** [comment]
@Smasher535 I hope that binary work

**Comment by ghost** [comment]
Me too :)

**Comment by fengberd** [comment]
That binary provided by php.net does NOT have some extensions which PocketMine requires.
So it will not work

**Comment by Johnmacrocraft** [comment]
@fengberd Then how about adding **Download binary from manual download url** feature? We can test binary not from your GitHub (_DOWNLOAD folder) if it's broken (like now). It's really annoying because I can't do anything to make Pocket Server's PHP7 work again.

**Comment by nnnlog** [comment]
@Johnmacrocraft @fengberd My think, too

@Johnmacrocraft 님이 PHP 바이너리 다운을 URL로 직접 다운하자는거죠?

**Comment by Johnmacrocraft** [comment]
@ParkChanSol 네, 거의 맞습니다.
번역: 그렇다면 **사용자 지정 링크에서 바이너리 다운로드** 기능을 추가하는 게 어떨까요? 그렇게 하면 바이너리가 고장났을 때 (지금 처럼) 당신 (fengberd)의 GitHub (_DOWNLOAD 폴더)에서 다운로드 하지 않고 테스트 할 수 있습니다. Pocket Server의 PHP7을 다시 작동하게 만들 수 있는 방법이 없다는 것이 너무 짜증납니다. (Pull Request 제외)

**Comment by nnnlog** [comment]
@Johnmacrocraft 음... 좋네요

Umm. It's good!

**Comment by ghost** [comment]
Umm? In which file is the link? I wanna change it to test... (i decompiled the app)

**Comment by fengberd** [comment]
Now you can try version 1.0.7.5 and install php manually.

**Comment by Johnmacrocraft** [comment]
@fengberd I see new update in releases tab, but it is not currently published to Google Play. Did you published it but there's some step to get released, or you forgot to do it? Also, If I pick non gz file extension file in Install PHP7 menu, does it change its file extension to gz? I tried installing php7 binary that isn't gz (It was xz, I just tried using it without renaming)

**Comment by fengberd** [comment]
You can only extract gz or xz and just select the executable binary...
I want to upload it to Google Play but have no time(I even published new version to GitHub on my way to school :/ )

**Comment by Johnmacrocraft** [comment]
@fengberd I don't want to spam on closed issues to annoy you or get ban, but it seems after v1.0.7.5 update all php7 binaries doesn't work. I tried some kind of them, and none of them worked!

**Comment by fengberd** [comment]
Are you sure about you tried binaries from itx-tech and extracted them?

**Comment by Johnmacrocraft** [comment]
@fengberd Wait... I need to extract it and install tar instead of gz? If so, I was wrong - it should work properly. Sorry.

**Comment by fengberd** [comment]
Yes you should...I added an alert in 1.0.7.6 to let user know that :P

**Comment by Smasher535** [comment]
Umm FENGberd? Could you give me a link for the "itx tech binary"?
