### ISSUE TITLE
0.16.x Installation Help

### ISSUE THREAD

**Issue by KevinLong021** [fengberd/MinecraftPEServer#43]
Now that genysis for 0.16.x is released I tried to reinstall genysis with the new update. All I got was a toast message that said ci.itxtech.org was not accessible. Is there another way I'm supposed to update my server or do I just need to wait for an app update?

-Mrfanman345

**Comment by nnnlog** [comment]
You should put PocketMine-MP.phar into yourself

**Comment by KevinLong021** [comment]
OK thnx I'll do that.

**Comment by KevinLong021** [comment]
Where do I find the Pocketmine-MP.phar ?
