### ISSUE TITLE
Where can I find the PocketMine-MP.phar to update to 0.16.x

### ISSUE THREAD

**Issue by KevinLong021** [fengberd/MinecraftPEServer#44]
Sorry if I'm asking too many obvious questions but where do I find the PocketMine-MP.phar for 0.16.x. I know genysis has updated but I'm not sure where to download this file or where to put it.
Sorry for my ignorance but hopefully someone can help me.
-Mrfanman345

**Comment by nnnlog** [comment]
See https://github.com/fengberd/MinecraftPEServer/issues/43

**Comment by KevinLong021** [comment]
Where do I find the download to this phar though?

**Comment by nnnlog** [comment]
You should download src, or Genisys' Gitlab

**Comment by KevinLong021** [comment]
OK so once I download the src  folder do I just paste it into the PocketMine folder?

**Comment by KevinLong021** [comment]
I managed to get it working thank you very much for all of your help!

**Comment by nnnlog** [comment]
You're. welcome~V~
