### ISSUE TITLE
Change binary supplying scheme

### ISSUE THREAD

**Issue by ishitatsuyuki** [fengberd/MinecraftPEServer#46]
1. GitHub is not a CDN.
  Embed the binary inside the app, so you can do arch-dependent deployment.
2. ARM is not the only architecture.
  Not to mention, there are many devices running arm64, or x86.
  We're friendly providing AArch64 binaries at https://itxtech.org/genisys/get/.

The usage of busybox is probably also redundant. Do not do the extraction on the device, much less using a command.

**Comment by nnnlog** [comment]
@ishitatsuyuki I always get PHP binary from your site(iTX-Tech)

**Comment by nnnlog** [comment]
@Johnmacrocraft
 @ishitatsuyuki 님이 무슨말 하고 계시는거에요...

**Comment by Johnmacrocraft** [comment]
@ParkChanSol
@ishitatsuyuki 님이 하신 말 번역:
1. GitHub는 CDN (콘텐츠 전송 네트워크 - https://ko.wikipedia.org/wiki/%EC%BD%98%ED%85%90%EC%B8%A0_%EC%A0%84%EC%86%A1_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC 참조)이 아닙니다.
   애플리케이션 내부에 바이너리를 포함시키면 아치 (architecture (아키텍처)를 말하신 거로 추정) 종속 배포를 할 수 있습니다.
2. ARM만이 유일한 아키텍처가 아닙니다.
   물론, arm64 또는 x86을 실행하는 많은 장치가 있습니다.
   저희는 https://itxtech.org/genisys/get/ 에서 AArch64 바이너리를 제공하고 있습니다.

**Comment by nnnlog** [comment]
@Johnmacrocraft 그럼  arm86 즉 32비트짜리를 사용해야 되겠네요

**Comment by Johnmacrocraft** [comment]
@ParkChanSol (말하는 걸 봐서 님도 아까 웹 사이트를 들어갔다 온 것처럼 보이기는 합니다만) 아까 1시간 전에 https://itxtech.org/genisys/get/ 들어가 보니까 Android / Raspberry Pi 탭에서 ARM (32 bit)와 AArch64 (64 bit)로 PHP7 7.0.13이 추가됐더군요.

**Comment by nnnlog** [comment]
@Johnmacrocraft 정확하게 조금 전은 아니고 @ishitatsuyuki 님이 올리고 나서 금방있다 봤습니다

**Comment by fengberd** [comment]
Sounds good,I want to add that feature this weekend or other time(If I can finish my homework :/)

**Comment by nnnlog** [comment]
@fengberd 
In Korea, Today is College Scholastic Ability Test.

I hope that you finish you homework :)

**Comment by ishitatsuyuki** [comment]
Can you guys put the daily life things to another place? Please do only technical discussions here.

**Comment by fengberd** [comment]
Of course. ?

**Comment by ishitatsuyuki** [comment]
Do not use GitHub for download; embed the binary inside the lib-[arch] directory instead.
