### ISSUE TITLE
PHP 5 is working,  but php 7 binary won't work

### ISSUE THREAD

**Issue by nnnlog** [fengberd/MinecraftPEServer#49]
I test that php 5 binary work, but php 7 binary doens't work.
It looks like app's problem

**Comment by Johnmacrocraft** [comment]
@ParkChanSol Nope, it works fine - You should use first version of php7 binary from fengberd (https://github.com/fengberd/MinecraftPEServer/blob/a96416728d7f182a7db3eef9f1c913a44c3229bf/_DOWNLOAD/php7.tar.gz).

**Comment by Johnmacrocraft** [comment]
@ParkChanSol Nope, it works fine - You should use first version of PHP7 binary from fengberd (아니요, 잘 작동합니다 - fengberd님이 첫번째로 올린 PHP7 바이너리를 사용해야 합니다.) (https://github.com/fengberd/MinecraftPEServer/blob/a96416728d7f182a7db3eef9f1c913a44c3229bf/_DOWNLOAD/php7.tar.gz).

**Comment by nnnlog** [comment]
@Johnmacrocraft hmm. Ok
