### ISSUE TITLE
PHP 7Binnary don`twork,

### ISSUE THREAD

**Issue by samp-pinch** [fengberd/MinecraftPEServer#52]

**Comment by samp-pinch** [comment]
In-game download php install php5,so onlz 0.15x works
Last one closed was true
Fix it
Do not give me tar.gz.fix inapp!!!

**Comment by Johnmacrocraft** [comment]
@NemanjaMAX Nope, it works fine if you download first version of php7 binary that fengberd uploaded to this repository. Because it's sightly hard to explain with only comment, so I won't explain how to do that. Please close this issue.

**Comment by nnnlog** [comment]
@Johnmacrocraft How to fix this error?

@fengberd I think @iTXTech 's  PHP binary doesn't work on MINECRAFTPESERVER.

**Comment by samp-pinch** [comment]
Yes don`t work...
I actually mean that ParkChan 😉

**Comment by nnnlog** [comment]
@NemanjaMAX I know, I think binary use @fengberd 's php binary

**Comment by samp-pinch** [comment]
Or give me full explain :)

**Comment by samp-pinch** [comment]
Il try on my rooted phone

**Comment by Johnmacrocraft** [comment]
@NemanjaMAX @ParkChanSol
1. Download php7 binary from here: https://github.com/fengberd/MinecraftPEServer/blob/a96416728d7f182a7db3eef9f1c913a44c3229bf/_DOWNLOAD/php7.tar.gz?raw=true
2. Extract php7.tar from php7.tar.gz, and extract php7 from php7.tar.
3. Install it.
4. Enjoy your server! :)
***Please note: You can't use xbox auth with this php7 binary.***

**Comment by nnnlog** [comment]
@Johnmacrocraft I knew that. :)

**Comment by ghost** [comment]
@NemanjaMAX how did you fix it?

**Comment by Johnmacrocraft** [comment]
@AnkitM252 Could you please read my last comment?

**Comment by ghost** [comment]
I already got it working

**Comment by Johnmacrocraft** [comment]
@NemanjaMAX @fengberd This issue can be closed as there's a solution.
