### ISSUE TITLE
Please help!! 

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#55]
Nukkit.jar in the sdcard/Nukkit
A NukkitLibrary in the sdcard.. 

[PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/data/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/sdcard0/Nukkit/Nukkit.jar, enable-ansi, disable-jline] Working Directory: /storage/sdcard0/Nukkit Environment: [ANDROID_ROOT=/system, LOOP_MOUNTPOINT=/mnt/obb, USBOTG_STORAGE=/storage/usbotg, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/sdcard0, TMPDIR=/storage/sdcard0/Nukkit/tmp, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=9, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar, ANDROID_PROPERTY_WORKSPACE=8,0, ANDROID_STORAGE=/storage]

**Comment by fengberd** [comment]
Mount java library FIRST
