### ISSUE TITLE
Not work!!

### ISSUE THREAD

**Issue by eemu2005** [fengberd/MinecraftPEServer#56]
Problem is here:    [PE Server] Unable to start Java.
java.io.IOException: Error running exec(). Command: [/data/data/net.fengberd.minecraftpe_server/java/jre/bin/java, -jar, /storage/sdcard0/Nukkit/Nukkit.jar, enable-ansi, disable-jline] Working Directory: /storage/sdcard0/Nukkit Environment: [ANDROID_ROOT=/system, LOOP_MOUNTPOINT=/mnt/obb, USBOTG_STORAGE=/storage/usbotg, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/sdcard0, TMPDIR=/storage/sdcard0/Nukkit/tmp, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, ANDROID_SOCKET_zygote=9, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin, ANDROID_DATA=/data, ANDROID_ASSETS=/system/app, ASEC_MOUNTPOINT=/mnt/asec, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-telephony-common.jar, ANDROID_PROPERTY_WORKSPACE=8,0, ANDROID_STORAGE=/storage]    

And i mounted java library FIRST!!!!!

**Comment by nnnlog** [comment]
Did you root your phone?

**Comment by eemu2005** [comment]
Yes

**Comment by eemu2005** [comment]
I use kingroot and selected ku.sud

**Comment by dracarch** [comment]
The same problem I had

**Comment by fengberd** [comment]
I dont know,it doesn't support some new android versions and I can't fix them because my highest android version is 4.4...

**Comment by PeratX** [comment]
This is because you are using the JDK doesn't match your CPU architecture or System Env.
