### ISSUE TITLE
About Java Library

### ISSUE THREAD

**Issue by TheDiamondYT1** [fengberd/MinecraftPEServer#57]
I need the following information **please**:

* Can you give me the link to where you downloaded it
* Is it the JRE or JDK?
* How come when i download from oracle the folder structure is different
* Why do we need to bind java lib folder to /lib?

**Comment by fengberd** [comment]
- About the link please see README.md
- It's JRE,if you want to get JDK please download from Oracle's website
- You should only make sure that the app can mount lib and access the java binary correctly
- Becalse java isn't interested in LD_LIBRARY_PATH,and just look for its library in /lib...

**Comment by TheDiamondYT1** [comment]
K
