### ISSUE TITLE
Project Die?

### ISSUE THREAD

**Issue by nnnlog** [fengberd/MinecraftPEServer#59]
@fengberd didn't work... Does this project die?

**Comment by SuperOP535** [comment]
Since PocketMine and a lot of mcpe server forks/spoons stopped supporting 32 bit the app is a bit useless

**Comment by fengberd** [comment]
There's lots of 64 bit phones isn't it?
:/


Best Regards,
FENGberd

**Comment by nnnlog** [comment]
@fengberd I don't know.. Now pocketmine support only php 7

**Comment by SuperOP535** [comment]
The app is php7 bro

**Comment by SuperOP535** [comment]
Well for me the app worked until pmmp dropped 32 bit support (I used old binary)

**Comment by Johnmacrocraft** [comment]
I think this issue can be closed because @fengberd is back?

**Comment by Johnmacrocraft** [comment]
Damn, It seems like my phone is 32bit. I'm done.

**Comment by nnnlog** [comment]
@fengberd is back!

**Comment by fengberd** [comment]
I just made a small update :P.
Now I must study for the final exam.
