### ISSUE TITLE
Cant download the new genisys...

### ISSUE THREAD

**Issue by Yoyu666** [fengberd/MinecraftPEServer#6]
Pls fix this

**Comment by Yoyu666** [comment]
这是什么问题？

**Comment by HyGlobalHD** [comment]
@fengberd can u fix this

**Comment by Yoyu666** [comment]
genisys remove the page,so it no work now at other places download!

**Comment by fengberd** [comment]
Genisys's jenkins died...Check this website:
http://jenkins.mcper.cn

**Comment by HyGlobalHD** [comment]
@fengberd Genisys Jenkins server revived so can you fix the app?
