### ISSUE TITLE
New website, new package?

### ISSUE THREAD

**Issue by SuperOP535** [fengberd/MinecraftPEServer#60]
Current package: net.fengberd.minecraftpeserver
fengberd.net doesn't exist.. make it to your new website btw I know it will cause problems but just try it, maybe googleplay supports new packages for same app but if it doesn't, package is not important

**Comment by fengberd** [comment]
The package name is same,don't worry.I just updated the package name of
classes.And both berd.moe and fengberd.net is mine.

**Comment by Johnmacrocraft** [comment]
@SuperOP535 @fengberd I think this issue can be closed now as there's an answer?
Also, the website isn't always ready, why we can't get it working lol?
