### ISSUE TITLE
Porting For Windows Phone 10 Mobile

### ISSUE THREAD

**Issue by RubenOliveira8** [fengberd/MinecraftPEServer#65]
Can you make a version for windows phone 10, Because I have one, and wanted to use it as a pocketmine server. Thx :)

**Comment by fengberd** [comment]
No such intend in current because windows phone requires C# skills and this is a Java project for android.

**Comment by RubenOliveira8** [comment]
Java is only for nukkit, i just wanna pocketmine, no nukkit, you need just
to compile php to work on the windows 10 mobile

**Comment by fengberd** [comment]
Alright,it seems that windows 10 mobile can run apks due to my google result.
I don't know how to compile that binary too,can you please ask iTX Tech for help?

**Comment by RubenOliveira8** [comment]
No windows 10 mobile cannot run apks anymore, microsoft removed the
compatibility, sorry for my bad english.
