### ISSUE TITLE
Can't run nukkit 

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#68]
![_20170903_111312](https://user-images.githubusercontent.com/25569806/30001796-0efbf754-9099-11e7-9ef4-854d933542bf.JPG)
![screenshot_2017-09-03-11-12-37](https://user-images.githubusercontent.com/25569806/30001795-0a1b9410-9099-11e7-9fa8-c3a807f488e9.png)

**Comment by fengberd** [comment]
You may not mounted java library correctly or not put your Nukkit.jar into
/sdcard/Nukkit
If you're sure about you've done all above,I have no idea about this
problem.Maybe you're trying to run java for arm on a x86 device?


Best Regards,
FENGberd
