### ISSUE TITLE
Cant Set Up Server 

### ISSUE THREAD

**Issue by TwistedAsylumMC** [fengberd/MinecraftPEServer#70]
Im Trying To SetUp My server With Genisyspro, how do i accept the license? 
![screenshot_2017-09-08-22-55-11](https://user-images.githubusercontent.com/30378179/30232635-fc93721e-94e8-11e7-8b4b-782079048f8e.png)

**Comment by fengberd** [comment]
Send "Y" for 2 times(don't type anything else before you finish it)
