### ISSUE TITLE
Cant Start Server

### ISSUE THREAD

**Issue by TwistedAsylumMC** [fengberd/MinecraftPEServer#71]
Im Trying To Start My Server, And It Keeps Crashing! Crash Log:
[CrashDump_Sat_Sep_9-21.11.26-CST_2017.log.zip](https://github.com/fengberd/PocketServer/files/1289806/CrashDump_Sat_Sep_9-21.11.26-CST_2017.log.zip)

**Comment by fengberd** [comment]
GenisysPro from ZXDA jenkins have some problems in current...[image: Inline
image 1]
I deleted the newest build just now,download GenisysPro again then it
should work!


Best Regards,
FENGberd

**Comment by TwistedAsylumMC** [comment]
Its Still Broken, Same Error Happens

**Comment by fengberd** [comment]
Use 1.0.9.4 please,old version will get cached phar because our CDN is not
smart enough about such situation.

**Comment by TwistedAsylumMC** [comment]
what?

**Comment by fengberd** [comment]
Upgrade your app to version 1.0.9.4 and "download GenisysPro again then it
should work!"
