### ISSUE TITLE
PHP 7.2 Binaries

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#73]
When i try start dropped this error.
This is the las update from SpigotPE

[CRITICAL] You must use PHP >= 7.2
[CRITICAL] Please use the installer provided on the homepage.
[PE Server] Server start failed!
[PE Server] Killing server...
[CRITICAL] You must use PHP >= 7.2
[CRITICAL] Please use the installer provided on the homepage.
[PE Server] Server start failed!

**Comment by fengberd** [comment]
There's no 7.2 binaries in current...Use Nukkit or GenisysPro instead


Best Regards,
FENGberd

**Comment by ghost** [comment]
Yea! I do it!
Thanks
