### ISSUE TITLE
Randomly dying...

### ISSUE THREAD

**Issue by samp-pinch** [fengberd/MinecraftPEServer#76]
When start server there is 90% chance that server will kill itself (its not cuz software, its happening on randomly places sometime before "Server started in blabla secconds" or sometimes after, example (I tested it without plugins and I tested 10.9.5 and 1.0.9.4 and its same):

(!W I TESTED ON GENISYSPRO AND LEVERYL)

15:42:10 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
       ##\    _                           _ 
      ## /   | | _____   _____ _ __ _   _| |
     ## /    | |/ _ \ \ / / _ \ '__| | | | |
    ## /     | |  __/\ V /  __/ |  | |_| | |
   ## /      |_|\___| \_/ \___|_|   \__, |_|
  ## /                              |___/   
 #########\ GitHub.com/LeverylTeam/Leveryl  
 \________/
15:42:10 [INFO] Loading properties and configuration...
15:42:10 [INFO] OpenSSL Extension Loaded!
15:42:10 [DEBUG] Server unique ID: f6cdc6f4-845a-3780-8df7-d56603d90ccd
15:42:10 [DEBUG] Machine unique ID: 500f5751-c2c0-3378-8dac-61b743cccdf3
15:42:10 [DEBUG] Process ID: 3623
15:42:11 [INFO] Leveryl is distributed under the GPL License version 3 and later
15:42:14 [INFO] No resource packs loaded.
15:42:15 [INFO] Loading source plugin PurePerms v1.4.0-INDEV
15:42:15 [NOTICE] PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 
15:42:15 [INFO] [PurePerms] Setting default language to 'en'
15:42:15 [NOTICE] [PurePerms] Multiworld support is currently disabled.
15:42:15 [NOTICE] [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
15:42:15 [INFO] Loading source plugin PureChat v1.4.0
15:42:16 [INFO] Preparing level "world"
15:42:16 [INFO] Preparing level "nether"
15:42:16 [INFO] Preparing level "ender"
15:42:16 [INFO] Enabling PurePerms v1.4.0-INDEV
15:42:16 [NOTICE] [PurePerms] Set data provider to YAMLv1.
15:42:16 [INFO] Enabling PureChat v1.4.0
15:42:16 [NOTICE] [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[PE Server] Server was stopped.
[PE Server] Killing server...
======
Sometimes server properly start but when I join ig its again kself
======
OS: Android (ofc lel)
Php: 7.0.14 from itxtech.org (I tested app's and PocketMine's php its same)
App version: 7.0.15
Plugins: Tested without em

**Comment by samp-pinch** [comment]
Now properly started after about 4-5 tries:
=====

15:53:29 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
       ##\    _                           _ 
      ## /   | | _____   _____ _ __ _   _| |
     ## /    | |/ _ \ \ / / _ \ '__| | | | |
    ## /     | |  __/\ V /  __/ |  | |_| | |
   ## /      |_|\___| \_/ \___|_|   \__, |_|
  ## /                              |___/   
 #########\ GitHub.com/LeverylTeam/Leveryl  
 \________/
15:53:29 [INFO] Loading properties and configuration...
15:53:29 [INFO] OpenSSL Extension Loaded!
15:53:29 [DEBUG] Server unique ID: f6cdc6f4-845a-3780-8df7-d56603d90ccd
15:53:29 [DEBUG] Machine unique ID: 500f5751-c2c0-3378-8dac-61b743cccdf3
15:53:29 [DEBUG] Process ID: 5231
15:53:29 [INFO] Leveryl is distributed under the GPL License version 3 and later
15:53:32 [INFO] No resource packs loaded.
15:53:32 [INFO] Loading source plugin PurePerms v1.4.0-INDEV
15:53:32 [NOTICE] PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 
15:53:32 [INFO] [PurePerms] Setting default language to 'en'
15:53:32 [NOTICE] [PurePerms] Multiworld support is currently disabled.
15:53:32 [NOTICE] [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
15:53:32 [INFO] Loading source plugin PureChat v1.4.0
15:53:32 [INFO] Preparing level "world"
15:53:32 [INFO] Preparing level "nether"
15:53:32 [INFO] Preparing level "ender"
15:53:32 [INFO] Enabling PurePerms v1.4.0-INDEV
15:53:33 [NOTICE] [PurePerms] Set data provider to YAMLv1.
15:53:33 [INFO] Enabling PureChat v1.4.0
15:53:33 [NOTICE] [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
15:53:33 [INFO] Starting GS4 status listener
15:53:33 [INFO] Setting query port to 19132
15:53:33 [INFO] Query running on 0.0.0.0:19132
=====


Let's try join:
=====

15:53:29 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
       ##\    _                           _ 
      ## /   | | _____   _____ _ __ _   _| |
     ## /    | |/ _ \ \ / / _ \ '__| | | | |
    ## /     | |  __/\ V /  __/ |  | |_| | |
   ## /      |_|\___| \_/ \___|_|   \__, |_|
  ## /                              |___/   
 #########\ GitHub.com/LeverylTeam/Leveryl  
 \________/
15:53:29 [INFO] Loading properties and configuration...
15:53:29 [INFO] OpenSSL Extension Loaded!
15:53:29 [DEBUG] Server unique ID: f6cdc6f4-845a-3780-8df7-d56603d90ccd
15:53:29 [DEBUG] Machine unique ID: 500f5751-c2c0-3378-8dac-61b743cccdf3
15:53:29 [DEBUG] Process ID: 5231
15:53:29 [INFO] Leveryl is distributed under the GPL License version 3 and later
15:53:32 [INFO] No resource packs loaded.
15:53:32 [INFO] Loading source plugin PurePerms v1.4.0-INDEV
15:53:32 [NOTICE] PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 
15:53:32 [INFO] [PurePerms] Setting default language to 'en'
15:53:32 [NOTICE] [PurePerms] Multiworld support is currently disabled.
15:53:32 [NOTICE] [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
15:53:32 [INFO] Loading source plugin PureChat v1.4.0
15:53:32 [INFO] Preparing level "world"
15:53:32 [INFO] Preparing level "nether"
15:53:32 [INFO] Preparing level "ender"
15:53:32 [INFO] Enabling PurePerms v1.4.0-INDEV
15:53:33 [NOTICE] [PurePerms] Set data provider to YAMLv1.
15:53:33 [INFO] Enabling PureChat v1.4.0
15:53:33 [NOTICE] [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
15:53:33 [INFO] Starting GS4 status listener
15:53:33 [INFO] Setting query port to 19132
15:53:33 [INFO] Query running on 0.0.0.0:19132
15:53:33 [INFO] Done (4.851s)! For help, type "help" or "?"
15:55:32 [DEBUG] Receiving Connection from: 192.168.1.73:53635
15:55:58 [DEBUG] [PurePerms] Registering player xxAdmin...
15:55:58 [INFO] xxAdmin[/192.168.1.73:53635] [ClientID: 7.4341568635058E+18] logged in with entity id 1 at (world, 128, 70, 128)
[PE Server] Server was stopped.
=====

**Comment by samp-pinch** [comment]
Umm @fengberd

**Comment by fengberd** [comment]
Can't solve,I EVEN DON'T KNOW WHY IT WAS STOPPED....
