### ISSUE TITLE
I can't build this project

### ISSUE THREAD

**Issue by ljuwon321** [fengberd/MinecraftPEServer#8]
i wanna building apk this project using **Android Studio,**
but This project have some error.
plz edit this project and fix that.
i'm sorry to my bad english.

**Comment by fengberd** [comment]
Check your depends if they aren't downloaded automatically

**Comment by TheDiamondYT1** [comment]
I can build it in AIDE for Android (Which doesnt build most projects) and Android Studio

**Comment by fengberd** [comment]
I'm using AIDE,there's no problem with build this project.
