### ISSUE TITLE
Add Apollo

### ISSUE THREAD

**Issue by MiguelPlayzMC** [fengberd/MinecraftPEServer#80]
Please add Apollo here is the Link [this](https://github.com/Apollo-SoftwareTeam/Apollo-Legacy)

**Comment by fengberd** [comment]
Trying to add it to our jenkins,btw the jenkins only supports PHP
7.0,PHP7.2 just exit with GLIBC too old error.
Do you have any idea about it or just a jenkins server that build this
project?



Best Regards,
FENGberd

**Comment by AnUnknownPerson** [comment]
I think he means add it to the list of software's

**Comment by fengberd** [comment]
Now our jenkins have Apollo building job btw Android doesn't support php7.2
in current,I can't find any suitable build...

**Comment by fengberd** [comment]
Bump.
https://github.com/fengberd/PocketServer/commit/1fa2a9e2aeef1920f3a90dd1dfc93664b8110f82
