### ISSUE TITLE
Php 7.2

### ISSUE THREAD

**Issue by xXIKhaledIXx** [fengberd/MinecraftPEServer#81]
Please Someone tell me how to install PHP 7.2 on Pocket Server ( i use android)

**Comment by xXIKhaledIXx** [comment]
I really need it

**Comment by fengberd** [comment]
Can you build it?If you can just send it to me.


Best Regards,
FENGberd

**Comment by PeratX** [comment]
Use buildroot to manually cross compile PHP 7.2

**Comment by xXIKhaledIXx** [comment]
THANKS! I will see
