### ISSUE TITLE
Can't use command in Nukkit

### ISSUE THREAD

**Issue by maqa588** [fengberd/MinecraftPEServer#82]
我是一名中国人，通过VPN下载到了此应用。Java运行库是arm版本的，换了很多的nukkit核心玩家也无法使用指令，很头疼。虽然跟朋友联机足够，但是我希望此问题能获得解决。

**Comment by maqa588** [comment]
You can use google translate,edtior.

**Comment by maqa588** [comment]
Phone:Xiaomi Redmi Note 4X

**Comment by maqa588** [comment]
日志：

ERROR: ld.so: object 'libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
'
07:45:37 [INFO] Loading nukkit.yml...
07:45:38 [INFO] Loading server properties...
07:45:38 [INFO] Selected English (eng) as the base language
07:45:38 [INFO] Starting Minecraft: PE server version v1.2.2
07:45:38 [INFO] Opening server on 0.0.0.0:19132
;37;1m" (API 1.0.0)
07:45:38 [INFO] Nukkit is distributed under the LGPL License
07:45:40 [INFO] Loading recipes...
07:45:40 [INFO] Loaded 415 recipes.
07:45:40 [INFO] Successfully loaded 0 resource packs
07:45:40 [INFO] Loading RsFunction v1.0.2
07:45:41 [INFO] Loading RsMoney v1.0.1
07:45:41 [INFO] Loading RsAuto v1.3.8
07:45:41 [INFO] Loading RsShop v1.0.0
07:45:41 [INFO] Loading RsSell v1.0.0
07:45:41 [INFO] Enabling RsFunction v1.0.2
07:45:41 [INFO] [RsFunction] You will use :zh
07:45:41 [INFO] Preparing level "world"
Nov 08, 2017 7:45:41 AM io.netty.channel.DefaultChannelId defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: c3:fe:ad:43:68:75:26:73
07:45:41 [INFO] Enabling RsMoney v1.0.1
07:45:41 [INFO] Enabling RsAuto v1.3.8
07:45:41 [INFO] [RsAuto] RsAuto is Loaded
07:45:41 [INFO] Enabling RsShop v1.0.0
07:45:41 [INFO] Enabling RsSell v1.0.0
07:45:41 [INFO] Starting GS4 status listener
07:45:41 [INFO] Setting query port to 19132
07:45:41 [INFO] Query is running on 0.0.0.0:19132
07:45:41 [INFO] Default game type: Survival Mode

**Comment by maqa588** [comment]
当试图输入指令的日志：

07:48:07 [INFO] PunctualWeb3377[/127.0.0.1:49878] logged in with entity id 53 at (world, 126.8679, 80.0, 129.6507)
07:48:08 [INFO] PunctualWeb3377 joined the game
07:48:16 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 28
	at cn.nukkit.utils.BinaryStream.getByte(BinaryStream.java:198)
	at cn.nukkit.utils.VarInt.read(VarInt.java:64)
	at cn.nukkit.utils.VarInt.readUnsignedVarLong(VarInt.java:141)
	at cn.nukkit.utils.VarInt.readVarLong(VarInt.java:125)
	at cn.nukkit.utils.BinaryStream.getVarLong(BinaryStream.java:353)
	at cn.nukkit.network.protocol.CommandRequestPacket.decode(CommandRequestPacket.java:38)
	at cn.nukkit.network.Network.processBatch(Network.java:154)
	at cn.nukkit.Player.handleDataPacket(Player.java:1985)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:998)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by fengberd** [comment]
直接炸在读取varint了,估计是游戏版本和服务端对不上

**Comment by maqa588** [comment]
Thank you.I was using mcpe beta edition.
