### ISSUE TITLE
Add PHP 7.2 Support

### ISSUE THREAD

**Issue by sero583** [fengberd/MinecraftPEServer#85]

**Comment by sero583** [comment]
@fengberd

**Comment by fengberd** [comment]
@PeratX emmmm


Best Regards,
FENGberd

**Comment by sero583** [comment]
@fengberd If its easy would be nice if it would be added because many users cant use anymore pmmp and so on (the forks)

**Comment by fengberd** [comment]
Buildroot haven't updated for PHP7.2 so I can't do that.
:(


Best Regards,
FENGberd

**Comment by sero583** [comment]
@fengberd ugh :/ Does it needs long to be updated for it?

**Comment by ghost** [comment]
@fengberd here i have 32bit 7.2 php  https://drive.google.com/open?id=17smVk4bU3vtazSnJaVJ7OZ9JlPTRTHml

**Comment by ghost** [comment]
its compiled for apollo app but well am going share it (:

**Comment by Frago9876543210** [comment]
@fengberd you can use this binary for arm v8. http://vipmcpe.ru/bin/bin.zip

**Comment by Frago9876543210** [comment]
![im](https://vgy.me/s2HzrD.png)

**Comment by Johnmacrocraft** [comment]
@Icey-girl The server stops without any error message on console when I use arm binary, any idea?

**Comment by ghost** [comment]
I got faked -_- It's 7.0 I try compile my self

**Comment by fengberd** [comment]
So does it works?



Best Regards,
FENGberd

**Comment by PeratX** [comment]
I tried to cross compile PHP 7.2. But it stuck on php_ini.c and threw an exception.

**Comment by fengberd** [comment]
We gave up,there's tons of errors during the compile progress...
I would be appreciated if anyone can fix them and compile an working binary...

**Comment by sero583** [comment]
@fengberd Maybe take a look at <a href="https://play.google.com/store/apps/details?id=com.esminis.server.php">this App which has support for PHP 7.2</a>

**Comment by Johnmacrocraft** [comment]
@sero583 I've already looked at it before, but binaries from the website of that application (where application downloads PHP binary) don't have enough extensions to run PocketMine-MP. One good thing is that at least it gives me PHP extension not found message instead of server just failing to start, which means that binary actually works on my device.

**Comment by sero583** [comment]
@Johnmacrocraft Well we see it's possible. Maybe idk contact the developer of that and ask how he did with hoping that he answers.
