### ISSUE TITLE
Java mount failed

### ISSUE THREAD

**Issue by Kuroeks** [fengberd/MinecraftPEServer#86]
I opened a server Nukkit with Magisk root and or worked, i uninstalled Magisk and i have installed normal root and when i try to start server it give me  an error: Java.lang.runtimeexception: mount failed.... PS: i have tried ti uninstall the app but nothing....Sorry for the bad english and reply quickly

**Comment by fengberd** [comment]
No idea,if you're using systemless root please move files that in lib folder of the nukkit_library.tar.gz into /system/fake-libs and try again.
