### ISSUE TITLE
php 7.0 64bit

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#90]
can that be added i got the php file if you wanth

**Comment by ghost** [comment]
[php 64bit android.zip](https://github.com/fengberd/PocketServer/files/1649018/php.64bit.android.zip)

**Comment by xXIKhaledIXx** [comment]
Its not working please someond fix it i'll die and find a way to fix it

**Comment by ghost** [comment]
@xXIKhaledIXx i dont fix any thing i dont have linux so i cant compile it

**Comment by fengberd** [comment]
Fixed in [v1.1.0.0](https://github.com/fengberd/PocketServer/releases/tag/v1.1.0.0)
