### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by xXIKhaledIXx** [fengberd/MinecraftPEServer#91]
Please can someone give me a link for php 7.2 binary file to use it on Pocket Server??

**Comment by ghost** [comment]
Its impossible as they say 
It hasn't been created yet

https://forums.pmmp.io/threads/php-7-2-0rc3-for-android.4867/

**Comment by ghost** [comment]
This php 7.2 u are talking about it only works on ×64 bit device 
Which a regular android isn't 
Becuase android is ×32 bit 

So this php does not exist yet !

**Comment by Frago9876543210** [comment]
You can use my builds
https://drive.google.com/open?id=1KK5NeQgVmhE6THUf-uVVsqW5msRzZ7t2

**Comment by lukeeey** [comment]
@Toxic190 Android can be 32 bit of 64 bit

**Comment by bzdnd** [comment]
I want to know how to install php7.2.3.. at the pocketserver

**Comment by fengberd** [comment]
Fixed in [v1.1.0.0](https://github.com/fengberd/PocketServer/releases/tag/v1.1.0.0)
