### ISSUE TITLE
Bubble water breathing meter (Genisys pro 1.1 dev) pocketserver

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#92]
In pocketserver app I downloaded genisys pro 1.1 dev official 
I downloaded php 7.0.3 
And run the server 
Everything was fine and good
But
When I enter the server on mcpe 
On any version from (1.1.0 - 1.1.5 - 1.1.7) (All)
I see the bubble water breathing meter always shown below the hunger meter 
May I ask why ?
First Im not any where near water 
So how could u suffocate without water ?

Fix this soon please.

**Comment by fengberd** [comment]
This is something should be solved by iTX Tech instead of me,please go here:https://github.com/GenisysPro/GenisysPro
