### ISSUE TITLE
Pocket server v 1.0.9.5 download process lost when switching to landscape mode.

### ISSUE THREAD

**Issue by fazalzahri** [fengberd/MinecraftPEServer#94]
# Expected behavior
while downloading the server, the ability to switch to landscape mode does not remove or cancel the server's ongoing download process.

# Actual behavior
When the server downloading process is in progress, I do the screen orientation or switch to landscape display mode, suddenly the server download notification window visible on the android device screen automatically disappears, so that the download process is finished or running is unknowable.

# How to reproduce
1. open and launch the app
2. click the top right shortcut
3. Download server
4. select one of the servers
5. switch to landscape mode
6. problems will appear

Browser:  vivo yt53
Operating system: lollipop 6.0.1
App version: V 1.0.9.5

# Recording Of The Bug
https://youtu.be/M9chlLU0hPg

**Comment by fengberd** [comment]
Patched here(I tried DialogFragment but it doesn't work so I'll use this method instead):
https://github.com/fengberd/PocketServer/blob/d8001202d99c4c8b23b1fab9c2e070c27532475b/app/src/main/java/moe/berd/pocket_server/fragment/MainFragment.java#L130-L143
