### ISSUE TITLE
Pocket Server (For MCPE) v 1.0.9.5 server type PocketMine in android 7.0 The Stop Server feature is not working

### ISSUE THREAD

**Issue by ammarraisafti** [fengberd/MinecraftPEServer#95]
#### Expected behavior
After installing PHP, then download the server, and press Start Server. Ability to Stop the Server must be possible by clicking the Stop Server feature.

#### Actual behavior
After press the Start Server, then I want to stop the Server. I tried clicking the Stop Server feature, but unfortunately, the Stop Server feature does not work.

#### How to reproduce
* Launch app. 

* Go to settings, Install PHP.

* Exit settings, check PocketMine in Server Type.

* Click the shortcut icon, press Download Server. 

* Select the server you want to use. 

* Press Start Server. 

* Press Stop Server, you will find the problem as I have explained.

**Browser: Samsung Galaxy S6 edge**
**Operating system: Nougat 7.0**
**App version: 1.0.9.5**

#### Recording Of The Bug
https://youtu.be/zkzOUme52Qc

**Comment by fengberd** [comment]
During my test,the function works properly on my Google Pixel XL(7.1.2).
Btw I can't give you an video because I just started it successfully for 1 time :cry: 
If you type some command in console works,this function should works too.
Please leave me your server software name and I'll check it out.

**Comment by fengberd** [comment]
Should be fixed in [v1.1.0.0](https://github.com/fengberd/PocketServer/releases/tag/v1.1.0.0)
